import { Camera, LogOut, PackageCheck, Save } from 'lucide-react'
import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import { money, shortDate } from '../lib/format'

export default function Account({ user }) {
  const [mode,setMode]=useState('signin'); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState(''); const [profile,setProfile]=useState(null); const [orders,setOrders]=useState([]); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false)
  useEffect(()=>{ if(user) loadAccount() },[user])
  async function loadAccount(){const [{data:p},{data:o}]=await Promise.all([supabase.from('profiles').select('*').eq('id',user.id).maybeSingle(),supabase.from('orders').select('*,order_items(*)').eq('user_id',user.id).order('created_at',{ascending:false})]);setProfile(p);setName(p?.full_name||'');setOrders(o||[])}
  async function authenticate(e){e.preventDefault();setBusy(true);setMessage('');const result=mode==='signup'?await supabase.auth.signUp({email,password,options:{data:{full_name:name}}}):await supabase.auth.signInWithPassword({email,password});setMessage(result.error?.message || (mode==='signup'?'Account created. Check your email if confirmation is enabled.':'Welcome back.'));setBusy(false)}
  async function saveProfile(e){e.preventDefault();setBusy(true);const {error}=await supabase.from('profiles').upsert({id:user.id,full_name:name,phone:profile?.phone||''});setMessage(error?.message||'Profile saved.');if(!error)loadAccount();setBusy(false)}
  async function uploadAvatar(file){if(!file)return;setBusy(true);const ext=file.name.split('.').pop();const path=`${user.id}/avatar.${ext}`;const {error}=await supabase.storage.from('avatars').upload(path,file,{upsert:true});if(error){setMessage(error.message);setBusy(false);return}const {data}=supabase.storage.from('avatars').getPublicUrl(path);await supabase.from('profiles').update({avatar_url:data.publicUrl}).eq('id',user.id);setMessage('Profile image updated.');await loadAccount();setBusy(false)}
  if(!user) return <main className="authPage"><div className="authVisual"><span>PRIVATE CLIENT / 01</span></div><form className="authForm" onSubmit={authenticate}><span className="eyebrow">ATELIER ACCOUNT</span><h1>{mode==='signin'?'Welcome back.':'Join the private edit.'}</h1><p>Save favourites, sync your bag and follow every order.</p>{mode==='signup'&&<input placeholder="Full name" value={name} onChange={e=>setName(e.target.value)} required/>}<input type="email" placeholder="Email address" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" minLength="6" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/><button disabled={busy} className="primaryButton full">{busy?'Please wait…':mode==='signin'?'Sign in':'Create account'}</button>{message&&<div className="inlineNotice">{message}</div>}<button type="button" className="linkButton" onClick={()=>{setMode(mode==='signin'?'signup':'signin');setMessage('')}}>{mode==='signin'?'New to Atelier? Create an account':'Already a client? Sign in'}</button></form></main>
  return <main className="accountPage"><header className="pageIntro compact"><span className="eyebrow">PRIVATE CLIENT</span><h1>Your <em>Atelier.</em></h1><p>{user.email}</p></header><div className="accountGrid"><section className="profileCard"><div className="avatarWrap">{profile?.avatar_url?<img src={profile.avatar_url} alt="Profile"/>:<span>{(name||user.email)[0]?.toUpperCase()}</span>}<label><Camera/><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>uploadAvatar(e.target.files?.[0])}/></label></div><form onSubmit={saveProfile}><h2>Profile</h2><label>Full name<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Phone<input value={profile?.phone||''} onChange={e=>setProfile({...profile,phone:e.target.value})} placeholder="Optional"/></label><button disabled={busy} className="secondaryButton"><Save/> Save profile</button></form><button className="linkButton danger" onClick={()=>supabase.auth.signOut()}><LogOut/> Sign out</button>{message&&<div className="inlineNotice">{message}</div>}</section><section className="ordersCard"><div className="sectionTitle"><div><span className="eyebrow">ORDER HISTORY</span><h2>Recent orders</h2></div><PackageCheck/></div>{orders.length?orders.map(order=><article className="orderRow" key={order.id}><div><b>#{order.id.slice(0,8).toUpperCase()}</b><span>{shortDate(order.created_at)} · {order.order_items?.length||0} pieces</span></div><div><span className={`status ${order.status}`}>{order.status}</span><strong>{money(order.total)}</strong></div></article>):<div className="emptyOrders"><p>No orders yet. Your completed portfolio checkouts will appear here.</p></div>}</section></div></main>
}
