import { ArrowRight, Minus, Plus, Trash2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { money } from '../lib/format'
import { StatePanel } from '../components/StatePanel'

export default function Cart({ cart, onQuantity, onRemove }) {
  const subtotal = cart.reduce((sum,x)=>sum+Number(x.products?.price||0)*x.quantity,0); const shipping = subtotal >= 300 ? 0 : 18
  return <main className="cartPage"><header className="pageIntro compact"><span className="eyebrow">YOUR SELECTION</span><h1>Shopping bag <em>({cart.length})</em></h1></header>{!cart.length ? <StatePanel title="Your bag is beautifully empty" copy="Discover pieces selected for the season." action={<Link className="textLink" to="/shop">Explore the collection <ArrowRight/></Link>}/> : <div className="cartLayout"><section className="cartItems">{cart.map(item=><article className="cartItem" key={item.id}><img src={item.products?.image_url} alt={item.products?.name}/><div className="cartInfo"><span className="eyebrow">ATELIER EDIT</span><h3>{item.products?.name}</h3><p>{item.color || 'Signature'} · {item.size || 'One size'}</p><div className="quantity"><button onClick={()=>onQuantity(item,item.quantity-1)}><Minus/></button><span>{item.quantity}</span><button onClick={()=>onQuantity(item,item.quantity+1)}><Plus/></button></div></div><strong>{money(Number(item.products?.price||0)*item.quantity)}</strong><button className="removeButton" aria-label="Remove item" onClick={()=>onRemove(item.id)}><Trash2/></button></article>)}</section><aside className="summaryCard"><span className="eyebrow">ORDER SUMMARY</span><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>Delivery</span><b>{shipping ? money(shipping) : 'Complimentary'}</b></div><div className="summaryTotal"><span>Total</span><b>{money(subtotal+shipping)}</b></div><Link className="primaryButton full" to="/checkout">Secure checkout</Link><p>Taxes included where applicable. No real payment is collected in this portfolio build.</p></aside></div>}</main>
}
