import { CheckCircle2, LockKeyhole } from 'lucide-react'
import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { money } from '../lib/format'

export default function Checkout({ user, cart, onRefresh }) {
  const navigate=useNavigate(); const [busy,setBusy]=useState(false); const [result,setResult]=useState(null); const subtotal=cart.reduce((s,x)=>s+Number(x.products?.price||0)*x.quantity,0); const shipping=subtotal>=300?0:18; const total=subtotal+shipping
  async function placeOrder(e){e.preventDefault();if(!user){navigate('/account');return}if(!cart.length)return;setBusy(true);setResult(null);const address=Object.fromEntries(new FormData(e.currentTarget));const {data:order,error}=await supabase.from('orders').insert({user_id:user.id,subtotal,shipping,total,shipping_address:address}).select().single();if(error){setResult({error:error.message});setBusy(false);return}const items=cart.map(x=>({order_id:order.id,product_id:x.product_id,product_name:x.products.name,unit_price:x.products.price,quantity:x.quantity,size:x.size,color:x.color}));const {error:itemError}=await supabase.from('order_items').insert(items);if(itemError){setResult({error:itemError.message});setBusy(false);return}await supabase.from('cart_items').delete().eq('user_id',user.id);await onRefresh();setResult({id:order.id});setBusy(false)}
  if(result?.id)return <main className="checkoutPage"><div className="checkoutSuccess"><CheckCircle2/><span className="eyebrow">ORDER SECURED</span><h1>Thank you.</h1><p>Your portfolio order reference is <b>#{result.id.slice(0,8).toUpperCase()}</b>. The order is now stored in Supabase and visible in your account.</p><Link className="primaryButton" to="/account">View account</Link></div></main>
  return <main className="checkoutPage"><form className="checkoutForm" onSubmit={placeOrder}><span className="eyebrow">SECURE CHECKOUT</span><h1>Delivery details</h1><div className="formGrid"><input name="first_name" placeholder="First name" required/><input name="last_name" placeholder="Last name" required/><input className="wide" name="address" placeholder="Address" required/><input name="city" placeholder="City" required/><input name="postcode" placeholder="Postcode" required/><input className="wide" name="country" placeholder="Country" required/></div><div className="portfolioPayment"><LockKeyhole/><div><b>Portfolio-safe checkout</b><p>This project demonstrates the complete order flow without collecting or simulating real card credentials.</p></div></div>{result?.error&&<div className="inlineNotice error">{result.error}</div>}<button className="primaryButton full" disabled={busy||!cart.length}>{busy?'Securing order…':`Place portfolio order — ${money(total)}`}</button></form><aside className="checkoutSummary"><span className="eyebrow">YOUR ORDER</span>{cart.map(x=><div className="miniItem" key={x.id}><img src={x.products?.image_url}/><div><b>{x.products?.name}</b><span>{x.quantity} × {money(x.products?.price)}</span></div></div>)}<div className="summaryTotal"><span>Total</span><b>{money(total)}</b></div></aside></main>
}
