insert into public.categories(name,slug,description) values ('Women','women','Refined tailoring and fluid silhouettes.'),('Men','men','Quiet modern essentials with architectural proportion.'),('Objects','accessories','Leather goods and considered accessories.') on conflict(slug) do nothing;
insert into public.products(category_id,name,slug,description,price,compare_at_price,image_url,sizes,colors,stock,featured)
select c.id,v.name,v.slug,v.description,v.price,v.compare_at_price,v.image_url,v.sizes,v.colors,v.stock,v.featured from (values
('women','Noir Sculpted Blazer','noir-sculpted-blazer','A sharply sculpted wool-blend blazer with a softened shoulder and satin-lined interior.',385.00,450.00,'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?auto=format&fit=crop&w=1200&q=90',array['XS','S','M','L'],array['Noir','Ivory'],12,true),
('women','Silk Column Dress','silk-column-dress','Fluid silk column dress designed with a clean neckline and understated drape.',420.00,null,'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=1200&q=90',array['XS','S','M','L'],array['Oyster','Black'],8,true),
('men','Merino Atelier Knit','merino-atelier-knit','Fine-gauge merino knit with a relaxed architectural fit.',245.00,null,'https://images.unsplash.com/photo-1610652492500-ded49ceeb378?auto=format&fit=crop&w=1200&q=90',array['S','M','L','XL'],array['Stone','Ink'],17,true),
('men','Tailored Wool Trouser','tailored-wool-trouser','Pleated wool trousers cut with a long, precise line.',290.00,330.00,'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=1200&q=90',array['30','32','34','36'],array['Charcoal','Taupe'],15,false),
('accessories','Arc Leather Bag','arc-leather-bag','Structured top-handle bag in smooth full-grain leather with brushed metal hardware.',520.00,null,'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1200&q=90',array['One Size'],array['Espresso','Black'],10,true),
('accessories','Linea Watch','linea-watch','Minimal steel timepiece with a slim profile and monochrome dial.',610.00,null,'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=1200&q=90',array['One Size'],array['Steel'],6,false)
) as v(category_slug,name,slug,description,price,compare_at_price,image_url,sizes,colors,stock,featured) join public.categories c on c.slug=v.category_slug on conflict(slug) do nothing;
